import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";
import ResponsiveNavs from "./components/navbars/ResponsiveNavs";
import Footer from "./components/Footer";

const inter = Montserrat
({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Surest App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveNavs/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
